import type { User } from "@/types/user"

export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: "1",
    name: "LESOA Asandratriniaina",
    email: "lesoa.asa@zurcher.edu.mg",
    password: "1234qwerty",
    role: "admin",
    avatarInitials: "LA",
    status: "actif",
  },
  {
    id: "2",
    name: "RASAMIZAFY Simeon",
    email: "rasamizafy.sit@zurcher.edu.mg",
    password: "1234qwerty",
    role: "comptable",
    avatarInitials: "RS",
    status: "actif",
  },
  {
    id: "3",
    name: "RADONIAINA Voahary",
    email: "radoniaina.v@zurcher.edu.mg",
    password: "1234qwerty",
    role: "ouvrier",
    avatarInitials: "RV",
    status: "actif",
  },
  {
    id: "4",
    name: "RAKOTONDRAMANANA Fanja",
    email: "rakotondramanana.f@zurcher.edu.mg",
    password: "1234qwerty",
    role: "controleur_interne",
    avatarInitials: "RF",
    status: "actif",
  },
  {
    id: "5",
    name: "LESOA Hideout",
    email: "lesoa.hideout@zurcher.edu.mg",
    password: "1234qwerty",
    role: "magasinier",
    avatarInitials: "LH",
    status: "actif",
  },
  {
    id: "6",
    name: "RABEMANANJARA Hery",
    email: "rabemananjara.h@zurcher.edu.mg",
    password: "1234qwerty",
    role: "ouvrier",
    avatarInitials: "RH",
    status: "actif",
  },
  {
    id: "7",
    name: "ANDRIANARISOA Miora",
    email: "andrianarisoa.m@zurcher.edu.mg",
    password: "1234qwerty",
    role: "comptable",
    avatarInitials: "AM",
    status: "inactif",
  },
  {
    id: "8",
    name: "RANDRIAMAHEFA Tojo",
    email: "randriamahefa.t@zurcher.edu.mg",
    password: "1234qwerty",
    role: "magasinier",
    avatarInitials: "RT",
    status: "suspendu",
  },
]
